version: '3.8'

services:
  potato-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped